### PR TITLE
New method to add new column

### PR DESCRIPTION
**Pull request by TiTnOuK**
I added the functionnality to be able to add a new column.
For example, in case user would like to add an action column to edit, delete or whatever else without having to do it in javascript.

Example :

in javascript, add new column (in datatable init options)
```
columns: [
    { data: "action", orderable: false, searchable: false }
]
```

in php, use new method add
```
$dt->add('action', function($data){
    // return an edit link in new column action
    return "<a href='user.php?id=" . $data['id'] . "'>edit</a>";
});
```

### CODE REVIEW

**Comment by n1crack** [comment]
I'm not sure of this if this is necessary.
I do the same with: 
```

$dt->query("select id, column1, id as action");

$dt->edit('action', function($data){
    // return an edit link in new column action
    return "<a href='user.php?id=" . $data['id'] . "'>edit</a>";
});

```

**Comment by TiTnOuK** [comment]
It's just not very intuitive to do edit to add a column not out of the query. For me `edit()`, it's to modify a column resulting from the query and `add()` allows to add an extra column. Moreover, it adds a little more control over what you want to do exactly.

**Comment by n1crack** [comment]
Hm.. I'll leave this pull request here for a while. i want to think about it.

**Comment by n1crack** [comment]
since it has no effect on the core functionality, i think there is no problem adding this.

thank you.

**Pull request merged**
